In [1]:
import pandas as pd

file_name = 'processing_ready_data.xlsx'
df = pd.read_excel(io=file_name)

In [2]:
pd.options.display.max_columns = 50
df.drop(labels=['Unnamed: 0'], axis=1)
df[:5]

,Unnamed: 0,time,extreme_1,extreme_2,extreme_3,extreme_4,extreme_5,extreme_6,extreme_7,extreme_8,extreme_score,PPCS_1,PPCS_2,PPCS_3,PPCS_4,PPCS_5,PPCS_6,PPCS_score,PPCS_7,well-being,father_relations,mother_relations,friends_relations,romantic_life,sexual_life,reenacting,weekly_session,session_time,weekly_minutes,gender,age,faith_status,education,relationship_status,lives_with,occupation,in_relationship,believes_in_god
0,0,2021-12-22 17:23:15.047,6,5,3,1,2,2,1,2,2.308059,2,3,1,1,3,1,11,1,1,7.0,7.0,7,1,1,5,3.0,30.0,90.0,Kobieta,22,Nie,Wykształcenie wyższe,Singiel/singielka,Z rodzicami/rodziną,Żadne z powyższych,False,False
1,1,2021-12-22 17:52:37.564,4,4,4,2,1,2,1,1,1.968187,1,2,1,1,2,1,8,1,7,5.0,6.0,5,10,10,5,1.0,10.0,10.0,Kobieta,21,Tak,Wykształcenie wyższe,W związku,Z rodzicami/rodziną,Studiuję,True,True
2,2,2021-12-22 18:10:43.931,4,4,6,1,3,2,1,1,2.312831,1,7,1,2,1,1,13,3,9,1.0,10.0,10,10,10,8,2.0,10.0,20.0,Kobieta,24,Tak,Wykształcenie wyższe,Zaręczony/zaręczona,Z rodzicami/rodziną,Studiuję,True,True
3,3,2021-12-22 18:41:52.992,3,3,2,4,4,4,2,4,3.332980,2,4,1,2,1,1,11,5,6,7.0,8.0,7,9,9,7,1.0,25.0,25.0,Kobieta,21,"Tak, ale nie praktykującą",Wykształcenie średnie,Zaręczony/zaręczona,Z partnerem/partnerką,Studiuję i pracuję,True,True
4,4,2021-12-22 20:09:18.884,3,3,1,1,1,1,1,1,1.286320,2,3,2,3,3,2,15,1,10,10.0,10.0,8,10,10,2,1.0,10.0,10.0,Mężczyzna,29,Tak,Wykształcenie wyższe,W związku małżeńskim,Z partnerem/partnerką,Pracuję,True,True

In [5]:
def negative_bold(val):
    bold = 'bold' if 1 > abs(val) > 0.2 else ''
    return f'font-weight: {bold}'

correlation_items = ['extreme_score', 'PPCS_score', 'sexual_life', 'weekly_session', 'session_time', 'reenacting', 'well-being',
                     'father_relations', 'mother_relations', 'romantic_life', 'age', 'gender']

In [6]:
#EVERYONE

correlations_df = df[correlation_items].corr(method='spearman')

correlations_df = correlations_df[:6].style.applymap(negative_bold)

correlations_df

In [7]:
# MAN ONLY

correlations_male = df.loc[df['gender'] == 'Mężczyzna']
correlations_male = correlations_male[correlation_items].corr(method='pearson')

correlations_male = correlations_male[:6].style.applymap(negative_bold)
correlations_male

In [13]:
# WOMAN ONLY

correlations_female = df.loc[df['gender'] == 'Kobieta']
correlations_female = correlations_female[correlation_items].corr(method='pearson')

correlations_female = correlations_female[:6].style.applymap(negative_bold)
correlations_female

In [14]:
# OLDER THAN 23

correlations_age = df.loc[df['age'] > 23]
correlations_age = correlations_age[correlation_items].corr(method='pearson')

correlations_age = correlations_age[:6].style.applymap(negative_bold)
correlations_age

In [15]:
# YOUNGER THAN 23

correlations_age = df.loc[df['age'] < 23]
correlations_age = correlations_age[correlation_items].corr(method='pearson')

correlations_age = correlations_age[:6].style.applymap(negative_bold)
correlations_age

In [16]:
# BELIEVE IN GOD

correlations_age = df.loc[df['believes_in_god'] == True]
correlations_age = correlations_age[correlation_items].corr(method='spearman')

correlations_age = correlations_age[:6].style.applymap(negative_bold)
correlations_age

In [17]:
# DOESN'T BELIEVE IN GOD

correlations_god = df.loc[df['believes_in_god'] == False]
correlations_god = correlations_god[correlation_items].corr(method='spearman')

correlations_god = correlations_god[:6].style.applymap(negative_bold)
correlations_god

In [18]:
# IN RELATIONSHIP

correlations_age = df.loc[df['in_relationship'] == True]
correlations_age = correlations_age[correlation_items].corr(method='pearson')

correlations_age = correlations_age[:6].style.applymap(negative_bold)
correlations_age

In [19]:
# NOT IN RELATIONSHIP

correlations_age = df.loc[df['in_relationship'] == False]
correlations_age = correlations_age[correlation_items].corr(method='pearson')

correlations_age = correlations_age[:6].style.applymap(negative_bold)
correlations_age